[workspace]
authors = ["Justin Bois <bois@caltech.edu>"]
channels = ["conda-forge"]
name = "bootcamp"
platforms = ["osx-arm64", "linux-64", "win-64", "osx-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
black = ">=25.1.0,<26"
bokeh = ">=3.7.3,<4"
click = ">=8.2.1,<9"
colorcet = ">=3.1.0,<4"
dask-expr = ">=2.0.0,<3"
datashader = ">=0.18.2,<0.19"
holoviews = ">=1.21.0,<2"
hvplot = ">=0.12.0,<0.13"
hypothesis = ">=6.138.2,<7"
ipython = ">=9.4.0,<10"
ipywidgets = ">=8.1.7,<9"
jinja2 = ">=3.1.6,<4"
jsonschema = ">=4.25.0,<5"
jupyter = ">=1.1.1,<2"
jupyterlab = ">=4.4.6,<5"
jupyter_bokeh = ">=4.0.5,<5"
line_profiler = ">=5.0.0,<6"
matplotlib = ">=3.10.5,<4"
mypy = ">=1.17.1,<2"
netcdf4 = ">=1.7.2,<2"
numba = ">=0.61.2,<0.62"
numpy = ">=2.2.6,<3"
pandas = ">=2.3.1,<3"
pip = ">=25.2,<26"
pyserial = ">=3.5,<4"
pytest = ">=8.4.1,<9"
scikit-image = ">=0.25.2,<0.26"
scikit-learn = ">=1.7.1,<2"
scipy = ">=1.16.1,<2"
seaborn = ">=0.13.2,<0.14"
sympy = ">=1.14.0,<2"
toolz = ">=1.0.0,<2"
tqdm = ">=4.67.1,<5"
traitlets = ">=5.14.3,<6"
twine = ">=6.1.0,<7"
xarray = ">=2025.8.0,<2026"
pyarrow = ">=21.0.0,<22"
marimo = ">=0.13.6,<0.14"

[pypi-dependencies]
altair = ">=5.5.0, <6"
blackcellmagic = ">=0.0.2, <0.0.3"
bootcamp-utils = ">=0.0.7, <0.0.8"
iqplot = ">=0.3.7, <0.4"
jupyterlab-spellchecker = ">=0.8.4, <0.9"
multiprocess = ">=0.70.18, <0.71"
vega-datasets = ">=0.9.0, <0.10"
watermark = ">=2.5.0, <3"

[target.win-64.pypi-dependencies]
polars = ">=1.32.3, <2"

[target.linux-64.pypi-dependencies]
polars = ">=1.32.3, <2"

[target.osx-arm64.pypi-dependencies]
polars = ">=1.32.3, <2"

[target.osx-64.pypi-dependencies]
polars-lts-cpu = ">=1.32.3, <2"
